#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystems.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hourdesi_ims")]
	public partial class BookBarcodeEntryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertlib_Bookentry(lib_Bookentry instance);
    partial void Updatelib_Bookentry(lib_Bookentry instance);
    partial void Deletelib_Bookentry(lib_Bookentry instance);
    #endregion
		
		public BookBarcodeEntryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["hourdesi_imsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BookBarcodeEntryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookBarcodeEntryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookBarcodeEntryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BookBarcodeEntryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<lib_Bookentry> lib_Bookentries
		{
			get
			{
				return this.GetTable<lib_Bookentry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lib_Bookentry")]
	public partial class lib_Bookentry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _bookid;
		
		private string _CallNo;
		
		private string _AccessorNo;
		
		private string _SelfNo;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<int> _createdby;
		
		private System.Nullable<int> _SerialNo;
		
		private System.Data.Linq.Binary _BarCodeImage;
		
		private string _Barcode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbookidChanging(int value);
    partial void OnbookidChanged();
    partial void OnCallNoChanging(string value);
    partial void OnCallNoChanged();
    partial void OnAccessorNoChanging(string value);
    partial void OnAccessorNoChanged();
    partial void OnSelfNoChanging(string value);
    partial void OnSelfNoChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OncreatedbyChanging(System.Nullable<int> value);
    partial void OncreatedbyChanged();
    partial void OnSerialNoChanging(System.Nullable<int> value);
    partial void OnSerialNoChanged();
    partial void OnBarCodeImageChanging(System.Data.Linq.Binary value);
    partial void OnBarCodeImageChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    #endregion
		
		public lib_Bookentry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bookid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int bookid
		{
			get
			{
				return this._bookid;
			}
			set
			{
				if ((this._bookid != value))
				{
					this.OnbookidChanging(value);
					this.SendPropertyChanging();
					this._bookid = value;
					this.SendPropertyChanged("bookid");
					this.OnbookidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CallNo", DbType="NVarChar(100)")]
		public string CallNo
		{
			get
			{
				return this._CallNo;
			}
			set
			{
				if ((this._CallNo != value))
				{
					this.OnCallNoChanging(value);
					this.SendPropertyChanging();
					this._CallNo = value;
					this.SendPropertyChanged("CallNo");
					this.OnCallNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessorNo", DbType="VarChar(50)")]
		public string AccessorNo
		{
			get
			{
				return this._AccessorNo;
			}
			set
			{
				if ((this._AccessorNo != value))
				{
					this.OnAccessorNoChanging(value);
					this.SendPropertyChanging();
					this._AccessorNo = value;
					this.SendPropertyChanged("AccessorNo");
					this.OnAccessorNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SelfNo", DbType="VarChar(50)")]
		public string SelfNo
		{
			get
			{
				return this._SelfNo;
			}
			set
			{
				if ((this._SelfNo != value))
				{
					this.OnSelfNoChanging(value);
					this.SendPropertyChanging();
					this._SelfNo = value;
					this.SendPropertyChanged("SelfNo");
					this.OnSelfNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="Int")]
		public System.Nullable<int> createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNo", DbType="Int")]
		public System.Nullable<int> SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCodeImage", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary BarCodeImage
		{
			get
			{
				return this._BarCodeImage;
			}
			set
			{
				if ((this._BarCodeImage != value))
				{
					this.OnBarCodeImageChanging(value);
					this.SendPropertyChanging();
					this._BarCodeImage = value;
					this.SendPropertyChanged("BarCodeImage");
					this.OnBarCodeImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="NVarChar(50)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
